Add changes to make plugin work on ChartJS V2 & V3
kurkle/chartjs-plugin-gradient pull request #5
Opened 2021-07-19 12:26 UTC by devotox

2021-07-19 17:18 UTC, kurkle requested changes

2021-07-19 17:18 UTC, kurkle commented on src/index.js
> +  if(meta.controller) {
Both, v2 and v3 have `meta.controller`, so this in not a valid way to separate the versions.

`Chart.version` was introduced in v3, so could use that to separate.

2021-07-19 17:18 UTC, kurkle commented on src/index.js
> +function areaIsValid(area){
Why would this need to be changed?

2021-07-19 17:18 UTC, kurkle commented on src/index.js
> +
No need to re-style the code

2021-07-22 07:42 UTC, devotox commented
@kurkle Thanks for the review changes have been made

2021-07-22 08:33 UTC, kurkle requested changes

2021-07-22 08:33 UTC, kurkle commented on src/index.js
> +  if(chart.version) {
The version is in the constructor, not in the instance.
Could be for example: 
```js
const getScale = Chart.version 
  ? (meta, axis) => meta[axis + 'Scale'] 
  : (meta, axis) => meta.controller['_' + key + 'Scale'];
```

2021-07-26 11:15 UTC, kurkle approved these changes

2021-07-26 11:16 UTC, merged